spring.application.name=calorie-tracker-backend

spring.autoconfigure.exclude=\
org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
anthropic.api-key=${ANTHROPIC_API_KEY}